infra:
  brick:
    rate-limiter:
      name: "api"
      capacity: 5
      refill-tokens: 5
      refill-period: 1m
      bucket-ttl: 10m
      client-id-header: "X-Api-Key"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
